version: 2
jobs:
  release:
    docker:
      - image: cimg/node:18.18.0
    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn install
      - run: yarn release
workflows:
  version: 2
  release-workflow:
    jobs:
      - release:
          context: semantic-release
          filters:
            branches:
              only: master
